"""lembretes por push e registro de envios

Revision ID: 018ff10eff0a
Revises: 706aa33badb7
Create Date: 2026-09-29 16:01:23.636422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# As colunas de texto do SQLModel viram sqlmodel.sql.sqltypes.AutoString nos scripts
# gerados; sem este import a migracao quebra na hora de rodar.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '018ff10eff0a'
down_revision: Union[str, Sequence[str], None] = '706aa33badb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('outcome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'code', 'local_date')
    )
    op.create_index(op.f('ix_reminder_logs_local_date'), 'reminder_logs', ['local_date'], unique=False)
    op.create_index(op.f('ix_reminder_logs_user_id'), 'reminder_logs', ['user_id'], unique=False)
    op.add_column('profiles', sa.Column('reminder_meals', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('profiles', sa.Column('reminder_weigh_in', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('profiles', sa.Column('reminder_streak', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('profiles', sa.Column('time_zone', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'time_zone')
    op.drop_column('profiles', 'reminder_streak')
    op.drop_column('profiles', 'reminder_weigh_in')
    op.drop_column('profiles', 'reminder_meals')
    op.drop_index(op.f('ix_reminder_logs_user_id'), table_name='reminder_logs')
    op.drop_index(op.f('ix_reminder_logs_local_date'), table_name='reminder_logs')
    op.drop_table('reminder_logs')
    # ### end Alembic commands ###
