"""baseline

Revision ID: 06819c1bdc41
Revises: 
Create Date: 2026-08-03 15:23:59.574602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# As colunas de texto do SQLModel viram sqlmodel.sql.sqltypes.AutoString nos scripts
# gerados; sem este import a migracao quebra na hora de rodar.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '06819c1bdc41'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('locale', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plan', sa.Enum('free', 'premium', name='plan'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_user_id', sa.Integer(), nullable=False),
    sa.Column('addressee_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'blocked', name='connectionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['addressee_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connections_addressee_user_id'), 'connections', ['addressee_user_id'], unique=False)
    op.create_index(op.f('ix_connections_requester_user_id'), 'connections', ['requester_user_id'], unique=False)
    op.create_table('cycle_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('mode', sa.Enum('manual', 'by_date', name='cyclemode'), nullable=False),
    sa.Column('phase', sa.Enum('menstrual', 'follicular', 'ovulatory', 'luteal', name='cyclephase'), nullable=True),
    sa.Column('last_period_date', sa.Date(), nullable=True),
    sa.Column('cycle_length_days', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cycle_tracking_user_id'), 'cycle_tracking', ['user_id'], unique=True)
    op.create_table('diet_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('started_on', sa.Date(), nullable=False),
    sa.Column('objective', sa.Enum('lose_fat', 'maintain', 'gain_muscle', 'recomp', name='objective'), nullable=False),
    sa.Column('review_weeks', sa.Integer(), nullable=False),
    sa.Column('target_kcal', sa.Integer(), nullable=False),
    sa.Column('maintenance_kcal', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diet_periods_started_on'), 'diet_periods', ['started_on'], unique=False)
    op.create_index(op.f('ix_diet_periods_user_id'), 'diet_periods', ['user_id'], unique=False)
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('muscle_group', sa.Enum('chest', 'back', 'shoulders', 'biceps', 'triceps', 'legs', 'glutes', 'abs', 'calves', 'cardio', name='musclegroup'), nullable=False),
    sa.Column('equipment', sa.Enum('barbell', 'dumbbell', 'machine', 'cable', 'bodyweight', 'kettlebell', 'band', 'other', name='equipment'), nullable=False),
    sa.Column('kind', sa.Enum('strength', 'cardio', name='exercisekind'), nullable=False),
    sa.Column('level', sa.Enum('beginner', 'intermediate', 'expert', name='exerciselevel'), nullable=True),
    sa.Column('media_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('media_url2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_kind'), 'exercises', ['kind'], unique=False)
    op.create_index(op.f('ix_exercises_level'), 'exercises', ['level'], unique=False)
    op.create_index(op.f('ix_exercises_muscle_group'), 'exercises', ['muscle_group'], unique=False)
    op.create_index(op.f('ix_exercises_slug'), 'exercises', ['slug'], unique=False)
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('food', 'recipe', name='favoritekind'), nullable=False),
    sa.Column('ref_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favorites_kind'), 'favorites', ['kind'], unique=False)
    op.create_index(op.f('ix_favorites_ref_id'), 'favorites', ['ref_id'], unique=False)
    op.create_index(op.f('ix_favorites_user_id'), 'favorites', ['user_id'], unique=False)
    op.create_table('feedback_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('module', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_reports_created_at'), 'feedback_reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_feedback_reports_module'), 'feedback_reports', ['module'], unique=False)
    op.create_index(op.f('ix_feedback_reports_read'), 'feedback_reports', ['read'], unique=False)
    op.create_index(op.f('ix_feedback_reports_user_id'), 'feedback_reports', ['user_id'], unique=False)
    op.create_table('foods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sa.Enum('protein', 'carb', 'fruit', 'vegetable', 'dairy', 'legume', 'fat', 'beverage', 'sweet', 'prepared', 'supplement', 'other', name='foodcategory'), nullable=False),
    sa.Column('kcal', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('carbs_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('default_portion_g', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foods_category'), 'foods', ['category'], unique=False)
    op.create_index(op.f('ix_foods_slug'), 'foods', ['slug'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('sex', sa.Enum('male', 'female', name='sex'), nullable=False),
    sa.Column('activity_level', sa.Enum('sedentary', 'light', 'moderate', 'active', 'very_active', name='activitylevel'), nullable=False),
    sa.Column('objective', sa.Enum('lose_fat', 'maintain', 'gain_muscle', 'recomp', name='objective'), nullable=False),
    sa.Column('cut_intensity', sa.Enum('light', 'moderate', 'aggressive', name='cutintensity'), nullable=False),
    sa.Column('diet_enabled', sa.Boolean(), nullable=False),
    sa.Column('scale_mac', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('body_fat_target_pct', sa.Float(), nullable=True),
    sa.Column('body_comp_source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('servings', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipes_user_id'), 'recipes', ['user_id'], unique=False)
    op.create_table('routines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routines_user_id'), 'routines', ['user_id'], unique=False)
    op.create_table('share_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('to_user_id', sa.Integer(), nullable=False),
    sa.Column('item_kind', sa.Enum('recipe', 'food', name='shareditemkind'), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'declined', name='shareofferstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_share_offers_from_user_id'), 'share_offers', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_share_offers_to_user_id'), 'share_offers', ['to_user_id'], unique=False)
    op.create_table('shared_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('item_kind', sa.Enum('recipe', 'food', name='shareditemkind'), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('source_item_id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_items_owner_user_id'), 'shared_items', ['owner_user_id'], unique=False)
    op.create_table('standalone_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('time_of_day', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sa.Enum('running', 'cycling', 'walking', 'yoga', 'pilates', 'boxing', 'swimming', 'dance', 'other', name='standaloneactivitykind'), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('intensity', sa.Enum('light', 'moderate', 'hard', name='activityintensity'), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('kcal', sa.Float(), nullable=False),
    sa.Column('kcal_is_manual', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_standalone_activities_entry_date'), 'standalone_activities', ['entry_date'], unique=False)
    op.create_index(op.f('ix_standalone_activities_user_id'), 'standalone_activities', ['user_id'], unique=False)
    op.create_table('supplements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dose', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplements_user_id'), 'supplements', ['user_id'], unique=False)
    op.create_table('user_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_achievements_code'), 'user_achievements', ['code'], unique=False)
    op.create_index(op.f('ix_user_achievements_user_id'), 'user_achievements', ['user_id'], unique=False)
    op.create_table('water_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount_ml', sa.Integer(), nullable=False),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_water_logs_logged_at'), 'water_logs', ['logged_at'], unique=False)
    op.create_index(op.f('ix_water_logs_user_id'), 'water_logs', ['user_id'], unique=False)
    op.create_table('weight_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('source', sa.Enum('manual', 'ble', name='weightsource'), nullable=False),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.Column('fat_percentage', sa.Float(), nullable=True),
    sa.Column('fat_mass_kg', sa.Float(), nullable=True),
    sa.Column('skeletal_muscle_percentage', sa.Float(), nullable=True),
    sa.Column('skeletal_muscle_kg', sa.Float(), nullable=True),
    sa.Column('muscle_percentage', sa.Float(), nullable=True),
    sa.Column('muscle_mass_kg', sa.Float(), nullable=True),
    sa.Column('water_percentage', sa.Float(), nullable=True),
    sa.Column('water_mass_kg', sa.Float(), nullable=True),
    sa.Column('visceral_fat_index', sa.Float(), nullable=True),
    sa.Column('scale_bmr_kcal', sa.Integer(), nullable=True),
    sa.Column('waist_cm', sa.Float(), nullable=True),
    sa.Column('neck_cm', sa.Float(), nullable=True),
    sa.Column('hip_cm', sa.Float(), nullable=True),
    sa.Column('arm_cm', sa.Float(), nullable=True),
    sa.Column('thigh_cm', sa.Float(), nullable=True),
    sa.Column('chest_cm', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weight_logs_logged_at'), 'weight_logs', ['logged_at'], unique=False)
    op.create_index(op.f('ix_weight_logs_user_id'), 'weight_logs', ['user_id'], unique=False)
    op.create_table('diary_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.Enum('breakfast', 'pre_workout', 'post_workout', 'lunch', 'snack', 'dinner', 'supper', 'other', name='mealtype'), nullable=False),
    sa.Column('source', sa.Enum('food', 'recipe', name='entrysource'), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('grams', sa.Float(), nullable=True),
    sa.Column('name_snapshot', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kcal', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('carbs_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diary_entries_entry_date'), 'diary_entries', ['entry_date'], unique=False)
    op.create_index(op.f('ix_diary_entries_user_id'), 'diary_entries', ['user_id'], unique=False)
    op.create_table('exercise_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('locale', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_translations_exercise_id'), 'exercise_translations', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_exercise_translations_locale'), 'exercise_translations', ['locale'], unique=False)
    op.create_table('food_portions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('label_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('grams', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_portions_food_id'), 'food_portions', ['food_id'], unique=False)
    op.create_table('food_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('locale', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_translations_food_id'), 'food_translations', ['food_id'], unique=False)
    op.create_index(op.f('ix_food_translations_locale'), 'food_translations', ['locale'], unique=False)
    op.create_index(op.f('ix_food_translations_name'), 'food_translations', ['name'], unique=False)
    op.create_table('recipe_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('grams', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_ingredients_recipe_id'), 'recipe_ingredients', ['recipe_id'], unique=False)
    op.create_table('routine_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('routine_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('target_sets', sa.Integer(), nullable=False),
    sa.Column('target_reps', sa.Integer(), nullable=False),
    sa.Column('target_weight_kg', sa.Float(), nullable=True),
    sa.Column('target_duration_min', sa.Integer(), nullable=True),
    sa.Column('rest_seconds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routine_exercises_routine_id'), 'routine_exercises', ['routine_id'], unique=False)
    op.create_table('supplement_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('supplement_id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['supplement_id'], ['supplements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplement_logs_log_date'), 'supplement_logs', ['log_date'], unique=False)
    op.create_index(op.f('ix_supplement_logs_supplement_id'), 'supplement_logs', ['supplement_id'], unique=False)
    op.create_index(op.f('ix_supplement_logs_user_id'), 'supplement_logs', ['user_id'], unique=False)
    op.create_table('workout_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('routine_id', sa.Integer(), nullable=True),
    sa.Column('routine_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_sessions_started_at'), 'workout_sessions', ['started_at'], unique=False)
    op.create_index(op.f('ix_workout_sessions_user_id'), 'workout_sessions', ['user_id'], unique=False)
    op.create_table('session_exercise_swaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('routine_exercise_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['routine_exercise_id'], ['routine_exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_exercise_swaps_session_id'), 'session_exercise_swaps', ['session_id'], unique=False)
    op.create_table('set_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('duration_min', sa.Float(), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_set_logs_exercise_id'), 'set_logs', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_set_logs_session_id'), 'set_logs', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_set_logs_session_id'), table_name='set_logs')
    op.drop_index(op.f('ix_set_logs_exercise_id'), table_name='set_logs')
    op.drop_table('set_logs')
    op.drop_index(op.f('ix_session_exercise_swaps_session_id'), table_name='session_exercise_swaps')
    op.drop_table('session_exercise_swaps')
    op.drop_index(op.f('ix_workout_sessions_user_id'), table_name='workout_sessions')
    op.drop_index(op.f('ix_workout_sessions_started_at'), table_name='workout_sessions')
    op.drop_table('workout_sessions')
    op.drop_index(op.f('ix_supplement_logs_user_id'), table_name='supplement_logs')
    op.drop_index(op.f('ix_supplement_logs_supplement_id'), table_name='supplement_logs')
    op.drop_index(op.f('ix_supplement_logs_log_date'), table_name='supplement_logs')
    op.drop_table('supplement_logs')
    op.drop_index(op.f('ix_routine_exercises_routine_id'), table_name='routine_exercises')
    op.drop_table('routine_exercises')
    op.drop_index(op.f('ix_recipe_ingredients_recipe_id'), table_name='recipe_ingredients')
    op.drop_table('recipe_ingredients')
    op.drop_index(op.f('ix_food_translations_name'), table_name='food_translations')
    op.drop_index(op.f('ix_food_translations_locale'), table_name='food_translations')
    op.drop_index(op.f('ix_food_translations_food_id'), table_name='food_translations')
    op.drop_table('food_translations')
    op.drop_index(op.f('ix_food_portions_food_id'), table_name='food_portions')
    op.drop_table('food_portions')
    op.drop_index(op.f('ix_exercise_translations_locale'), table_name='exercise_translations')
    op.drop_index(op.f('ix_exercise_translations_exercise_id'), table_name='exercise_translations')
    op.drop_table('exercise_translations')
    op.drop_index(op.f('ix_diary_entries_user_id'), table_name='diary_entries')
    op.drop_index(op.f('ix_diary_entries_entry_date'), table_name='diary_entries')
    op.drop_table('diary_entries')
    op.drop_index(op.f('ix_weight_logs_user_id'), table_name='weight_logs')
    op.drop_index(op.f('ix_weight_logs_logged_at'), table_name='weight_logs')
    op.drop_table('weight_logs')
    op.drop_index(op.f('ix_water_logs_user_id'), table_name='water_logs')
    op.drop_index(op.f('ix_water_logs_logged_at'), table_name='water_logs')
    op.drop_table('water_logs')
    op.drop_index(op.f('ix_user_achievements_user_id'), table_name='user_achievements')
    op.drop_index(op.f('ix_user_achievements_code'), table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_index(op.f('ix_supplements_user_id'), table_name='supplements')
    op.drop_table('supplements')
    op.drop_index(op.f('ix_standalone_activities_user_id'), table_name='standalone_activities')
    op.drop_index(op.f('ix_standalone_activities_entry_date'), table_name='standalone_activities')
    op.drop_table('standalone_activities')
    op.drop_index(op.f('ix_shared_items_owner_user_id'), table_name='shared_items')
    op.drop_table('shared_items')
    op.drop_index(op.f('ix_share_offers_to_user_id'), table_name='share_offers')
    op.drop_index(op.f('ix_share_offers_from_user_id'), table_name='share_offers')
    op.drop_table('share_offers')
    op.drop_index(op.f('ix_routines_user_id'), table_name='routines')
    op.drop_table('routines')
    op.drop_index(op.f('ix_recipes_user_id'), table_name='recipes')
    op.drop_table('recipes')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_foods_slug'), table_name='foods')
    op.drop_index(op.f('ix_foods_category'), table_name='foods')
    op.drop_table('foods')
    op.drop_index(op.f('ix_feedback_reports_user_id'), table_name='feedback_reports')
    op.drop_index(op.f('ix_feedback_reports_read'), table_name='feedback_reports')
    op.drop_index(op.f('ix_feedback_reports_module'), table_name='feedback_reports')
    op.drop_index(op.f('ix_feedback_reports_created_at'), table_name='feedback_reports')
    op.drop_table('feedback_reports')
    op.drop_index(op.f('ix_favorites_user_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_ref_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_kind'), table_name='favorites')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_exercises_slug'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_muscle_group'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_level'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_kind'), table_name='exercises')
    op.drop_table('exercises')
    op.drop_index(op.f('ix_diet_periods_user_id'), table_name='diet_periods')
    op.drop_index(op.f('ix_diet_periods_started_on'), table_name='diet_periods')
    op.drop_table('diet_periods')
    op.drop_index(op.f('ix_cycle_tracking_user_id'), table_name='cycle_tracking')
    op.drop_table('cycle_tracking')
    op.drop_index(op.f('ix_connections_requester_user_id'), table_name='connections')
    op.drop_index(op.f('ix_connections_addressee_user_id'), table_name='connections')
    op.drop_table('connections')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
