"""compartilhar refeicao

Revision ID: 073c4a673f96
Revises: 5553ee741ea0
Create Date: 2026-09-24 07:13:16.417640

Refeicao do diario entra como terceiro tipo de oferta (alem de receita e alimento).
A oferta ganha dia e refeicao de origem, e os itens congelados no envio moram numa
tabela propria. O selo "Recebido de Fulana" reusa shared_items com o tipo novo
diary_entry.

Os enums entrysource e mealtype ja existem no banco: as colunas novas os reusam com
create_type=False, senao o CREATE TYPE quebraria.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# As colunas de texto do SQLModel viram sqlmodel.sql.sqltypes.AutoString nos scripts
# gerados; sem este import a migracao quebra na hora de rodar.
import sqlmodel
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '073c4a673f96'
down_revision: Union[str, Sequence[str], None] = '5553ee741ea0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Valor novo de enum precisa estar commitado antes de qualquer linha usar.
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE shareditemkind ADD VALUE IF NOT EXISTS 'meal'")
        op.execute("ALTER TYPE shareditemkind ADD VALUE IF NOT EXISTS 'diary_entry'")

    op.create_table('share_offer_meal_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('source', postgresql.ENUM(name='entrysource', create_type=False), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('kcal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['share_offers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_share_offer_meal_items_offer_id'), 'share_offer_meal_items', ['offer_id'], unique=False)
    op.add_column('share_offers', sa.Column('meal_date', sa.Date(), nullable=True))
    op.add_column('share_offers', sa.Column('meal_type', postgresql.ENUM(name='mealtype', create_type=False), nullable=True))
    op.alter_column('share_offers', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_share_offers_meal_date'), 'share_offers', ['meal_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_share_offers_meal_date'), table_name='share_offers')
    # ofertas de refeicao nao tem item_id: saem antes de a coluna voltar a NOT NULL
    op.execute("DELETE FROM share_offers WHERE item_kind = 'meal'")
    op.alter_column('share_offers', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('share_offers', 'meal_type')
    op.drop_column('share_offers', 'meal_date')
    op.drop_index(op.f('ix_share_offer_meal_items_offer_id'), table_name='share_offer_meal_items')
    op.drop_table('share_offer_meal_items')
    # Postgres nao remove valor de enum (nao existe DROP VALUE): 'meal' e
    # 'diary_entry' ficam no tipo como residuo, sem linha usando.
    op.execute("DELETE FROM shared_items WHERE item_kind = 'diary_entry'")
    # ### end Alembic commands ###
