"""Adiciona novidades do app (news_items e news_reads)

Revision ID: 214a5232d394
Revises: 8d47ef42a117
Create Date: 2026-08-21 16:03:32.649901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# As colunas de texto do SQLModel viram sqlmodel.sql.sqltypes.AutoString nos scripts
# gerados; sem este import a migracao quebra na hora de rodar.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '214a5232d394'
down_revision: Union[str, Sequence[str], None] = '8d47ef42a117'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('published_on', sa.Date(), nullable=False),
    sa.Column('importance', sa.Enum('normal', 'important', name='newsimportance'), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('title_pt_br', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body_pt_br', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title_es', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body_es', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_items_published'), 'news_items', ['published'], unique=False)
    op.create_index(op.f('ix_news_items_published_on'), 'news_items', ['published_on'], unique=False)
    op.create_table('news_reads',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'news_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news_reads')
    op.drop_index(op.f('ix_news_items_published_on'), table_name='news_items')
    op.drop_index(op.f('ix_news_items_published'), table_name='news_items')
    op.drop_table('news_items')
    # ### end Alembic commands ###
    # O autogenerate cria o tipo enum junto com a tabela mas nao o derruba: no Postgres
    # ele sobrevive ao drop_table e faz o upgrade seguinte falhar com "type already
    # exists". No SQLite o enum e so um VARCHAR, entao a chamada nao faz nada.
    sa.Enum(name='newsimportance').drop(op.get_bind(), checkfirst=True)
