"""pausa do treino nao conta no tempo

Revision ID: fb7483c77abc
Revises: 24361de46ac3
Create Date: 2026-08-27 14:41:44.667040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# As colunas de texto do SQLModel viram sqlmodel.sql.sqltypes.AutoString nos scripts
# gerados; sem este import a migracao quebra na hora de rodar.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fb7483c77abc'
down_revision: Union[str, Sequence[str], None] = '24361de46ac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_sessions', sa.Column('paused_at', sa.DateTime(), nullable=True))
    # server_default='0' preenche os treinos que ja existem (NOT NULL sem default
    # quebraria na tabela com linhas); depois removemos o default para o valor vir
    # sempre da aplicacao, igual as outras colunas.
    op.add_column(
        'workout_sessions',
        sa.Column('paused_seconds', sa.Integer(), nullable=False, server_default='0'),
    )
    # batch_alter_table porque o SQLite nao tem ALTER COLUMN: no Postgres sai o ALTER
    # normal, no SQLite o alembic recria a tabela. Mesmo padrao de
    # f8888d54dcd1_arquivar_rotinas_de_treino.
    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.alter_column('paused_seconds', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_sessions', 'paused_seconds')
    op.drop_column('workout_sessions', 'paused_at')
    # ### end Alembic commands ###
